name: ApiExceptionMiddleware

on:
  push:
    branches: [ "master" ]
    paths:
      - src/Df.ApiExceptionMiddleware/**
  pull_request:
    branches: [ "master" ]
    paths:
      - src/Df.ApiExceptionMiddleware/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Df.ApiExceptionMiddleware/Df.ApiExceptionMiddleware/Df.ApiExceptionMiddleware.csproj
    - name: Build
      run: dotnet build --no-restore src/Df.ApiExceptionMiddleware/Df.ApiExceptionMiddleware/Df.ApiExceptionMiddleware.csproj
    - name: Pack
      run: dotnet pack src/Df.ApiExceptionMiddleware/Df.ApiExceptionMiddleware/Df.ApiExceptionMiddleware.csproj -o out
    - name: Nuget push
      run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.TOKEN }} --source "github"
